### ISSUE TITLE
Keep getting error "mess is not defined"

### ISSUE THREAD

**Issue by Master1122334455** [JohnKearney1/MineGPT#1]
Really interesting project but I keep getting mess is not defined at line 103.

`const params = {
      messages: mess,
      max_tokens: 1000,
      temperature: 0.5,
      n: 1,
      stop: '',
      model: "gpt-3.5-turbo",
    };`

**Comment by JohnKearney1** [comment]
v2.1
- Fixes https://github.com/JohnKearney1/MineGPT/issues/1 ✅
- Added console logging for all chats and simplified debug info
- Refactored account info into `config.json` instead of keeping it inline
- Better error handling
- Removed redundant commands to make bot OP agnostic
- Created "quiet mode" for when a provided OpenAI API key is invalid (bot will only respond to commands, and will not query OpenAI)
- Updated Readme for better support
